- .circleci/announcePublish.sh
- .circleci/config.yml
- package-lock.json
- package.json
> Add GH release link to Slack

- package-lock.json
- package.json
- schema.graphql
- src/sdk/contract/internal/personal-account-registry.contract.ts
- src/sdk/dto/estimate-gateway-batch.dto.ts
- src/sdk/dto/estimate-gateway-known-op.dto.ts
- src/sdk/gateway/classes/gateway-estimated-batch.ts
- src/sdk/gateway/classes/gateway-estimated-known-op.ts
- src/sdk/gateway/classes/gateway-submitted-batch.ts
- src/sdk/gateway/gateway.service.ts
- src/sdk/sdk.ts
> Rename 'refund' with 'fee'

- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/ISSUE_TEMPLATE/-bug--bug-report.md
- .github/ISSUE_TEMPLATE/bug_report.md
> Update issue templates

- package-lock.json
- package.json
- src/sdk/api/api.service.ts
- src/sdk/api/constants.ts
- src/sdk/api/utils/map-api-result.ts
- src/sdk/assets/assets.service.ts
added and configed cache for graphql
> [BAC-936] optimise get token list tokens

- .github/workflows/run-linter-and-tests.yml
- package-lock.json
- package.json
[NodeJSScan](https://github.com/ajinabraham/nodejsscan) is an opensource static code analyzer. The results will be shown on `Security tab`
> Integrate nodejsscan - static code analyzer

- package-lock.json
- package.json
- src/sdk/dto/get-p2p-payment-channels-admin.dto.ts
> Fix: Super admin custom tokens

- package-lock.json
- package.json
- src/sdk/dto/get-cross-chain-bridge-route.dto.ts
- src/sdk/dto/get-cross-chain-bridge-token-list.dto.ts
- src/sdk/dto/get-exchange-supported-assets.dto.ts
- src/sdk/dto/index.ts
- src/sdk/exchange/exchange.service.ts
- src/sdk/sdk.ts
Changes made as Partha requested on etherspot channel
* Changed fromChainId and toChainId as mandatory in socket cross chain endpoint
* Added chainId as Optional to the getExchangeSupportedAssets Endpoint
> Feedback Changes

- .github/workflows/deploy-docs.yml
> Change SSH key

- pull_request_template.md
- Adding Pull Request template
- Following best development practices, PR description should explain in details changes proposed
- In a private repo
> Add Pull request template

- package-lock.json
- package.json
- src/sdk/sdk.ts
- src/sdk/transactions/classes/index.ts
- src/sdk/transactions/classes/known-contract.ts
- src/sdk/transactions/classes/known-contracts.ts
- src/sdk/transactions/constants.ts
- src/sdk/transactions/transactions.service.ts
- Added functions for registering and fetching registered wrapped supertokens
-
```
const sdk = new Sdk(randomWallet(), {
networkName: NetworkNames.Goerli,
env: EnvNames.LocalNets
});
const contract = await sdk.registerERC20WrapperToken("0x6c56bCCA445292C54E9cc048c9471d0A22bb4eee"); // super USDC on goerli
console.log(contract);
const tokens = await sdk.getRegisteredERC20WrapperTokens();
console.log(tokens);
const wrapper = await sdk.findSuperERC20WrapperOnChain("0x98339D8C260052B7ad81c28c16C0b98420f2B46a"); // USDC
console.log(wrapper);
```
> Save supertokens in db

- examples/src/19-exchange-using-fee-token.ts
- package-lock.json
- package.json
- src/sdk/env/constants.ts
- Added swap using Fee Token program in examples
- Added Magic Network for testing on main net support
-
-
-
-
> Fee Token Example

- package-lock.json
- package.json
- src/sdk/dto/get-exchange-cross-chain-quote.dto.ts
- src/sdk/exchange/constants.ts
- src/sdk/exchange/exchange.service.ts
- src/sdk/sdk.ts
- add option to select lifi bridges
-
-
-
-
> feat: add allowed lifi bridges

- examples/src/20-advance-routes-lifi.ts
- package-lock.json
- package.json
- src/sdk/dto/advance-routes-lifi.dto.ts
- src/sdk/dto/get-step-transactions-lifi.dto.ts
- src/sdk/dto/index.ts
- src/sdk/env/constants.ts
- src/sdk/exchange/classes/advance-routes-lifi.ts
- src/sdk/exchange/classes/index.ts
- src/sdk/exchange/classes/step-transactions-lifi.ts
- src/sdk/exchange/exchange.service.ts
- src/sdk/sdk.ts
- added new endpoints for advance routes in LiFi
-
- Tested locally and the transaction was successful https://polygonscan.com/tx/0x3519d600b38563a7edd764485c2c3e598287512882f41b8d843962e3db65ff05
-
-
> Advance Routes LiFi

- package-lock.json
- package.json
- schema.graphql
- src/sdk/env/constants.ts
- src/sdk/network/constants.ts
- Removed Kovan, Rinkeby, Ropsten, Op Kovan testiest as the networks are deprecated
-
-
-
-
> PRO-675 - Removed deprecated networks

- .github/workflows/run-static-code-anlayzer.yml
- Setting up CodeQL javascript security and quality scanning
- Improving static code analysis
- On a forked repo
> Setup CodeQL

- package-lock.json
- package.json
- src/sdk/context.ts
- src/sdk/contract/internal/__mocks__/gatewayV2.contract.ts
- src/sdk/contract/internal/gatewayV2.contract.ts
- src/sdk/contract/internal/index.ts
- src/sdk/contract/internal/personal-account-registry.contract.ts
- src/sdk/dto/custom-project-metadata.dto.ts
- src/sdk/env/constants.ts
- src/sdk/gateway/gateway.service.ts
- src/sdk/gateway/interfaces.ts
- src/sdk/sdk.ts
- Added a `guarded` property to `submitGateway` function's dto - this will make the batch revert if it wasn't submitted by one of our trusted relayers
-
-
-
-
> Add guarded tx in a batch

- package-lock.json
- package.json
- src/sdk/notification/constants.ts
- src/sdk/notification/interfaces.ts
- added a new notification type: `GatewayBatchResubmitted` - emitted on tx resubmission
-
-
-
-
> Add tx resubmission notification

- package-lock.json
- package.json
- src/sdk/gateway/gateway.service.ts
- made batches guarded by default
-
- Tested guarded batches on testnets
https://blockscout.com/poa/sokol//tx/0xb0d1417a76ecc65eec02949dd3037e2f5a2783546511c5ae59b0affd3b48776a
https://testnet.bscscan.com/tx/0x58fdf3df0b2bf0dd18f4b9ed17a0f522bd0dd4d64f0af69d8555b43fdaad050f
https://explorer.testnet.fantom.network/transactions/0x60701ab99183cea50a59bc42f03e08a6a4c97130df00b2a1158c175f291b8fc0
https://testnet.snowtrace.io/tx/0x6ec1d42b4941dc20739cb1f216c27b2025862a541916a6e112617410fa235bf8
https://goerli.etherscan.io/tx/0x605e91a3d42a4598d91253a9518bf6461c6bf437af73a53f0df66a71325bf7e7
> Guarded batch by default

- package-lock.json
- package.json
- src/sdk/dto/advance-routes-lifi.dto.ts
- src/sdk/dto/get-LiFi-status.dto.ts
- src/sdk/dto/index.ts
- src/sdk/exchange/classes/index.ts
- src/sdk/exchange/classes/lifi-status.ts
- src/sdk/exchange/exchange.service.ts
- src/sdk/sdk.ts
- Added new endpoint for getting status of cross chain transfer from LiFi
- Bumped the lifi sdk version
-
-
-
-
> LiFi updates

- .github/workflows/deploy-docs.yml
- .github/workflows/run-linter-and-tests.yml
- examples/src/21-exchange-rates.ts
- package-lock.json
- package.json
- src/sdk/rates/classes/rate-data.ts
- src/sdk/sdk.spec.ts
- src/sdk/sdk.ts
- Handling more than 50 tokens and sending data in batches and returning only unique tokens.
-
-
- This has been tested through SDK using example files
- We have passed around 1000+ tokens
- We have passed wrong tokens to verify empty results
> Feature/pro 901 implement batching for rates in SDK

- .husky/pre-commit
- .husky/pre-push
- package-lock.json
- package.json
- Added Husky pre-commit and pre-push hooks
- Following best DevOps practices 
- Locally on this branch
> Implement husky pre-commit and pre-push hooks

- package-lock.json
- package.json
- src/sdk/dto/get-exchange-cross-chain-quote.dto.ts
- src/sdk/exchange/exchange.service.ts
- src/sdk/sdk.ts
- added optional parameter toAddress on LiFi getQuotes API
-
- tested locally
-
-
> LiFi Get Quotes API Update

- package-lock.json
- package.json
- src/sdk/exchange/classes/exchange-bridging-quote.ts
- src/sdk/exchange/exchange.service.ts
- Returned LiFi tool used in getQuotes api to track the progress of bridge transaction status
-
-
-
-
> Returned Bridge tool used in getQuotes API

- src/sdk/dto/advance-routes-lifi.dto.ts
- src/sdk/dto/get-exchange-cross-chain-quote.dto.ts
- src/sdk/dto/get-exchange-offers.dto.ts
- src/sdk/exchange/exchange.service.ts
- src/sdk/sdk.ts
- added fromAddress and toAddress as optional fields in bridging and swapping apis
-
-
-
-
> Exchange API Updates

- package-lock.json
- package.json
> Bumped up the version

- package-lock.json
- package.json
- Updated the version of some of the packages
- Updated the version of some of the packages mentioned in the following PRs.
[#214 ](https://github.com/etherspot/etherspot-sdk/pull/214)
[#189 ](https://github.com/etherspot/etherspot-sdk/pull/189)
[#182 ](https://github.com/etherspot/etherspot-sdk/pull/182)
[#159 ](https://github.com/etherspot/etherspot-sdk/pull/159)
[#154 ](https://github.com/etherspot/etherspot-sdk/pull/154)
[#119 ](https://github.com/etherspot/etherspot-sdk/pull/119)
-
-  Tested in the local machine through the example files and it does not crash anything.
-
-
> Upgrade the package version

- package-lock.json
- package.json
- src/sdk/dto/advance-routes-lifi.dto.ts
- src/sdk/dto/get-exchange-cross-chain-quote.dto.ts
- src/sdk/dto/get-exchange-offers.dto.ts
- src/sdk/exchange/exchange.service.ts
- src/sdk/sdk.ts
- added optional parameter on all the swaps and cross chain apis in graphql
- Tested Locally
> 1055 - Added Optional parameter showZeroUsd

- src/sdk/env/constants.ts
- Added OP and ARB Mainnet Networks to QA environment to be available for everyone under MainnetsTest env on the sdk
> MainnetsTest Network Update

- package-lock.json
- package.json
- Updated package version to be released for klaytn network addition
> Updated package version for Klaytn Network

- package-lock.json
- package.json
- updated Etherspot contracts version where the oktc main net is deployed
> Updated Contracts Version

- examples/package.json
- examples/src/32-advance-routes.ts
- package-lock.json
- package.json
- schema.graphql
- src/sdk/dto/advance-routes.dto.ts
- src/sdk/dto/index.ts
- src/sdk/exchange/classes/advance-route.ts
- src/sdk/exchange/classes/advance-routes.ts
- src/sdk/exchange/classes/index.ts
- src/sdk/exchange/exchange.service.ts
- src/sdk/sdk.ts
- Added a new endpoint for advanceRoutes.
- This has been tested in the local environment
> Added advanceRoutes endpoint
